### ISSUE TITLE
[FEATURE] GoatCounter Notice

### ISSUE THREAD

**Issue by TheCedarPrince** [JuliaHealth/JuliaHealthBlog#10]
Hey @Hetarth02 ,

Would you be willing to add in another PR that adds a notice on the about.md page about GoatCounter? You could maybe adapt a notice from this: https://jacobzelko.com/#is_my_privacy_safe ? 

Thanks!

~ tcp :deciduous_tree:

**Comment by Hetarth02** [comment]
Sure

**Comment by TheCedarPrince** [comment]
You the bomb dot com @Hetarth02  :boom: !

**Comment by Hetarth02** [comment]
It's nothing much.😄
